export const mockUsers = {
  employee: {
    id: '1',
    fullName: 'NIRMAL NAIK',
    employeeId: '13574',
    role: 'employee',
    department: 'Digital Communications',
    designation: 'Department Assistant',
    email: 'nirmalnaik1402@gmail.com',
    isImcMember: false,
  },
  hod: {
    id: '2',
    fullName: 'Shubranshu Samal',
    employeeId: '11111',
    role: 'hod',
    department: 'Digital Communications',
    designation: 'HOD',
    email: 'shubranshu@jphrc.com',
    isImcMember: false,
  },
  imc: {
    id: '3',
    fullName: 'Incident Management Committee',
    employeeId: 'IMC',
    role: 'imc',
    department: 'Quality Management',
    designation: 'Committee',
    email: 'imc@jphrc.com',
  },
  head_management: {
    id: '4',
    fullName: 'Management Director',
    employeeId: 'JPHRC_MD',
    role: 'head_management',
    department: 'MD Office',
    email: 'md@jphrc.com',
  },
  system_admin: {
    id: '5',
    fullName: 'System Administrator',
    employeeId: 'JPHRC_ADMIN',
    role: 'system_admin',
    department: 'IT',
    email: 'admin@jphrc.com',
  },
  hod_medical_services: {
    id: '6',
    fullName: 'HOD Medical Services',
    employeeId: '11101',
    role: 'hod',
    department: 'Medical Services',
    designation: 'HOD',
    email: 'medicalservices@jphrc.com',
    isImcMember: false,
  },
  hod_nursing_services: {
    id: '7',
    fullName: 'HOD Nursing Services',
    employeeId: '11102',
    role: 'hod',
    department: 'Nursing Services',
    designation: 'HOD',
    email: 'nursingservices@jphrc.com',
    isImcMember: false,
  },
  hod_purchase: {
    id: '8',
    fullName: 'HOD Purchase',
    employeeId: '11103',
    role: 'hod',
    department: 'Purchase',
    designation: 'HOD',
    email: 'purchase@jphrc.com',
    isImcMember: false,
  },
  hod_finance_and_accounts: {
    id: '9',
    fullName: 'HOD Finance and Accounts',
    employeeId: '11104',
    role: 'hod',
    department: 'Finance and Accounts',
    designation: 'HOD',
    email: 'financeandaccounts@jphrc.com',
    isImcMember: false,
  },
  hod_public_relations: {
    id: '10',
    fullName: 'HOD Public Relations',
    employeeId: '11105',
    role: 'hod',
    department: 'Public Relations',
    designation: 'HOD',
    email: 'publicrelations@jphrc.com',
    isImcMember: false,
  },
  hod_legal_cell: {
    id: '11',
    fullName: 'HOD Legal Cell',
    employeeId: '11106',
    role: 'hod',
    department: 'Legal Cell',
    designation: 'HOD',
    email: 'legalcell@jphrc.com',
    isImcMember: false,
  },
  hod_corporate_relations_and_business_development: {
    id: '12',
    fullName: 'HOD Corporate Relations and Business Development',
    employeeId: '11107',
    role: 'hod',
    department: 'Corporate Relations and Business Development',
    designation: 'HOD',
    email: 'corporaterelationsandbusinessdevelopment@jphrc.com',
    isImcMember: false,
  },
  hod_human_resource: {
    id: '13',
    fullName: 'HOD Human Resource',
    employeeId: '11108',
    role: 'hod',
    department: 'Human Resource',
    designation: 'HOD',
    email: 'humanresource@jphrc.com',
    isImcMember: false,
  },
  hod_facility: {
    id: '14',
    fullName: 'HOD Facility',
    employeeId: '11109',
    role: 'hod',
    department: 'Facility',
    designation: 'HOD',
    email: 'facility@jphrc.com',
    isImcMember: false,
  },
  hod_food_and_beverages: {
    id: '15',
    fullName: 'HOD Food and Beverages',
    employeeId: '11110',
    role: 'hod',
    department: 'Food and Beverages',
    designation: 'HOD',
    email: 'foodandbeverages@jphrc.com',
    isImcMember: false,
  },
  hod_housekeeping: {
    id: '16',
    fullName: 'HOD Housekeeping',
    employeeId: '11111',
    role: 'hod',
    department: 'Housekeeping',
    designation: 'HOD',
    email: 'housekeeping@jphrc.com',
    isImcMember: false,
  },
  hod_linen_and_laundry: {
    id: '17',
    fullName: 'HOD Linen and Laundry',
    employeeId: '11112',
    role: 'hod',
    department: 'Linen and Laundry',
    designation: 'HOD',
    email: 'linenandlaundry@jphrc.com',
    isImcMember: false,
  },
  hod_ambulance_travel_transport: {
    id: '18',
    fullName: 'HOD Ambulance / Travel / Transport',
    employeeId: '11113',
    role: 'hod',
    department: 'Ambulance / Travel / Transport',
    designation: 'HOD',
    email: 'ambulancetraveltransport@jphrc.com',
    isImcMember: false,
  },
  hod_security_services: {
    id: '19',
    fullName: 'HOD Security Services',
    employeeId: '11114',
    role: 'hod',
    department: 'Security Services',
    designation: 'HOD',
    email: 'securityservices@jphrc.com',
    isImcMember: false,
  },
  hod_quality_management: {
    id: '20',
    fullName: 'HOD Quality Management',
    employeeId: '11115',
    role: 'hod',
    department: 'Quality Management',
    designation: 'HOD',
    email: 'qualitymanagement@jphrc.com',
    isImcMember: false,
  },
  hod_training_and_development: {
    id: '21',
    fullName: 'HOD Training and Development',
    employeeId: '11116',
    role: 'hod',
    department: 'Training and Development',
    designation: 'HOD',
    email: 'traininganddevelopment@jphrc.com',
    isImcMember: false,
  },
  hod_stores: {
    id: '22',
    fullName: 'HOD Stores',
    employeeId: '11117',
    role: 'hod',
    department: 'Stores',
    designation: 'HOD',
    email: 'stores@jphrc.com',
    isImcMember: false,
  },
  hod_fire_safety: {
    id: '23',
    fullName: 'HOD Fire Safety',
    employeeId: '11118',
    role: 'hod',
    department: 'Fire Safety',
    designation: 'HOD',
    email: 'firesafety@jphrc.com',
    isImcMember: false,
  },
  hod_patient_care: {
    id: '24',
    fullName: 'HOD Patient Care',
    employeeId: '11119',
    role: 'hod',
    department: 'Patient Care',
    designation: 'HOD',
    email: 'patientcare@jphrc.com',
    isImcMember: false,
  },
  hod_general_maintenance: {
    id: '25',
    fullName: 'HOD General Maintenance',
    employeeId: '11120',
    role: 'hod',
    department: 'General Maintenance',
    designation: 'HOD',
    email: 'generalmaintenance@jphrc.com',
    isImcMember: false,
  },
  hod_bio_medical: {
    id: '26',
    fullName: 'HOD Bio-Medical',
    employeeId: '11121',
    role: 'hod',
    department: 'Bio-Medical',
    designation: 'HOD',
    email: 'biomedical@jphrc.com',
    isImcMember: false,
  },
  hod_strategy_and_external_communications: {
    id: '27',
    fullName: 'HOD Strategy and External Communications',
    employeeId: '11122',
    role: 'hod',
    department: 'Strategy and External Communications',
    designation: 'HOD',
    email: 'strategyandexternalcommunications@jphrc.com',
    isImcMember: false,
  },
  hod_asset: {
    id: '28',
    fullName: 'HOD Asset',
    employeeId: '11123',
    role: 'hod',
    department: 'Asset',
    designation: 'HOD',
    email: 'asset@jphrc.com',
    isImcMember: false,
  },
  hod_jpiee: {
    id: '29',
    fullName: 'HOD JPIEE',
    employeeId: '11124',
    role: 'hod',
    department: 'JPIEE',
    designation: 'HOD',
    email: 'jpiee@jphrc.com',
    isImcMember: false,
  },
  hod_lab_medicine: {
    id: '30',
    fullName: 'HOD Lab Medicine',
    employeeId: '11125',
    role: 'hod',
    department: 'Lab Medicine',
    designation: 'HOD',
    email: 'labmedicine@jphrc.com',
    isImcMember: false,
  },
  hod_blood_centre: {
    id: '31',
    fullName: 'HOD Blood Centre',
    employeeId: '11126',
    role: 'hod',
    department: 'Blood Centre',
    designation: 'HOD',
    email: 'bloodcentre@jphrc.com',
    isImcMember: false,
  },
  hod_radiology: {
    id: '32',
    fullName: 'HOD Radiology',
    employeeId: '11127',
    role: 'hod',
    department: 'Radiology',
    designation: 'HOD',
    email: 'radiology@jphrc.com',
    isImcMember: false,
  },
  hod_md_office: {
    id: '33',
    fullName: 'HOD MD Office',
    employeeId: '11128',
    role: 'hod',
    department: 'MD Office',
    designation: 'HOD',
    email: 'mdoffice@jphrc.com',
    isImcMember: false,
  },
  hod_infection_control_and_microbiology: {
    id: '34',
    fullName: 'HOD Infection Control and Microbiology',
    employeeId: '11129',
    role: 'hod',
    department: 'Infection Control and Microbiology',
    designation: 'HOD',
    email: 'infectioncontrolandmicrobiology@jphrc.com',
    isImcMember: false,
  },
};

export const initialMockIncidents = [
  {
    id: 'JPHRC/IMS/2026/0001',
    reference_id: 'JPHRC/IMS/2026/0001',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Medical Services'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Non-compliance to doctors written order',
    incident_category: 'Nursing Document Related',
    incident_types: ['Non-compliance to doctors written order'],
    incident_categories: ['Nursing Document Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for Medical Services to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.303Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0002',
    reference_id: 'JPHRC/IMS/2026/0002',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Nursing Services'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Laundry and Linen related',
    incident_types: ['Others'],
    incident_categories: ['Laundry and Linen related'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for Nursing Services to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.303Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0003',
    reference_id: 'JPHRC/IMS/2026/0003',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Purchase'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Medicine and consumable related billing errors',
    incident_category: 'Billing Related',
    incident_types: ['Medicine and consumable related billing errors'],
    incident_categories: ['Billing Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Purchase to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.303Z"},{"action":"HOD Viewed","by":"HOD Purchase","timestamp":"2026-05-30T05:21:20.303Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0004',
    reference_id: 'JPHRC/IMS/2026/0004',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Finance and Accounts'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate shutdown',
    incident_category: 'Software/Hardware Related',
    incident_types: ['Inappropriate shutdown'],
    incident_categories: ['Software/Hardware Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Finance and Accounts to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.303Z"},{"action":"HOD Viewed","by":"HOD Finance and Accounts","timestamp":"2026-05-30T05:21:20.303Z"},{"action":"HOD Reviewed","by":"HOD Finance and Accounts","timestamp":"2026-06-04T05:21:20.303Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0005',
    reference_id: 'JPHRC/IMS/2026/0005',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Public Relations'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inebriated staff',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Inebriated staff'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for Public Relations to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.303Z"},{"action":"HOD Viewed","by":"HOD Public Relations","timestamp":"2026-05-30T05:21:20.303Z"},{"action":"HOD Reviewed","by":"HOD Public Relations","timestamp":"2026-06-04T05:21:20.303Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.303Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0006',
    reference_id: 'JPHRC/IMS/2026/0006',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Legal Cell'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Code Orange',
    incident_category: 'Hospital Emergency Codes Related',
    incident_types: ['Code Orange'],
    incident_categories: ['Hospital Emergency Codes Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Legal Cell to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.303Z"},{"action":"HOD Viewed","by":"HOD Legal Cell","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Legal Cell","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0007',
    reference_id: 'JPHRC/IMS/2026/0007',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Corporate Relations and Business Development'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Training & development related',
    incident_category: 'HR Related',
    incident_types: ['Training & development related'],
    incident_categories: ['HR Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor resolved incident reported for Corporate Relations and Business Development to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Corporate Relations and Business Development","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Corporate Relations and Business Development","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0008',
    reference_id: 'JPHRC/IMS/2026/0008',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'dispute',
    created_at: new Date(Date.now() - 23 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Human Resource'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Packaging and labelling related',
    incident_category: 'Blood Bank Related',
    incident_types: ['Packaging and labelling related'],
    incident_categories: ['Blood Bank Related'],
    occurred_to: 'Staff',
    description: 'Sample Major dispute incident reported for Human Resource to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Human Resource","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Human Resource","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0009',
    reference_id: 'JPHRC/IMS/2026/0009',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'redirect_requested',
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Facility'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Poor Quality of linen',
    incident_category: 'Laundry and Linen related',
    incident_types: ['Poor Quality of linen'],
    incident_categories: ['Laundry and Linen related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave redirect_requested incident reported for Facility to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Facility","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"Redirect Requested","by":"HOD Facility","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0010',
    reference_id: 'JPHRC/IMS/2026/0010',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Food and Beverages'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Splash of Hazardous/Infective Material',
    incident_category: 'Infection Control Related',
    incident_types: ['Splash of Hazardous/Infective Material'],
    incident_categories: ['Infection Control Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for Food and Beverages to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0011',
    reference_id: 'JPHRC/IMS/2026/0011',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Housekeeping'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Classification of Incident',
    incident_types: ['Others'],
    incident_categories: ['Classification of Incident'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for Housekeeping to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0012',
    reference_id: 'JPHRC/IMS/2026/0012',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Linen and Laundry'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Incorrect entry of investigation in system',
    incident_category: 'Nursing Document Related',
    incident_types: ['Incorrect entry of investigation in system'],
    incident_categories: ['Nursing Document Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Linen and Laundry to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Linen and Laundry","timestamp":"2026-05-30T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0013',
    reference_id: 'JPHRC/IMS/2026/0013',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Ambulance / Travel / Transport'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Unauthorized movement of facility item',
    incident_category: 'Facility Related',
    incident_types: ['Unauthorized movement of facility item'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Ambulance / Travel / Transport to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Ambulance / Travel / Transport","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Ambulance / Travel / Transport","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0014',
    reference_id: 'JPHRC/IMS/2026/0014',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Security Services'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Untimely delivery of linen',
    incident_category: 'Laundry and Linen related',
    incident_types: ['Untimely delivery of linen'],
    incident_categories: ['Laundry and Linen related'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for Security Services to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Security Services","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Security Services","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0015',
    reference_id: 'JPHRC/IMS/2026/0015',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Quality Management'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate documentation',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Inappropriate documentation'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Quality Management to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Quality Management","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Quality Management","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0016',
    reference_id: 'JPHRC/IMS/2026/0016',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Training and Development'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Damage to facility asset',
    incident_category: 'Facility Related',
    incident_types: ['Damage to facility asset'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor resolved incident reported for Training and Development to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Training and Development","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Training and Development","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0017',
    reference_id: 'JPHRC/IMS/2026/0017',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'dispute',
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Stores'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Injury/adverse outcomes to patient during procedure',
    incident_category: 'Surgery or Procedure Related',
    incident_types: ['Injury/adverse outcomes to patient during procedure'],
    incident_categories: ['Surgery or Procedure Related'],
    occurred_to: 'Staff',
    description: 'Sample Major dispute incident reported for Stores to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Stores","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Stores","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0018',
    reference_id: 'JPHRC/IMS/2026/0018',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'redirect_requested',
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Fire Safety'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Incorrect/inappropriate results Clinical correlation related',
    incident_category: 'Radiology Related',
    incident_types: ['Incorrect/inappropriate results Clinical correlation related'],
    incident_categories: ['Radiology Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave redirect_requested incident reported for Fire Safety to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Fire Safety","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"Redirect Requested","by":"HOD Fire Safety","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0019',
    reference_id: 'JPHRC/IMS/2026/0019',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Patient Care'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Network related',
    incident_category: 'Software/Hardware Related',
    incident_types: ['Network related'],
    incident_categories: ['Software/Hardware Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for Patient Care to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0020',
    reference_id: 'JPHRC/IMS/2026/0020',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['General Maintenance'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Damage to facility asset',
    incident_category: 'Facility Related',
    incident_types: ['Damage to facility asset'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for General Maintenance to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0021',
    reference_id: 'JPHRC/IMS/2026/0021',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Bio-Medical'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate use of vehicle',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Inappropriate use of vehicle'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Bio-Medical to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Bio-Medical","timestamp":"2026-05-30T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0022',
    reference_id: 'JPHRC/IMS/2026/0022',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Digital Communications'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Foreign matter in food',
    incident_category: 'Food and Beverages',
    incident_types: ['Foreign matter in food'],
    incident_categories: ['Food and Beverages'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Digital Communications to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Digital Communications","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Digital Communications","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0023',
    reference_id: 'JPHRC/IMS/2026/0023',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 23 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Strategy and External Communications'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Government credit patient related billing error',
    incident_category: 'Billing Related',
    incident_types: ['Government credit patient related billing error'],
    incident_categories: ['Billing Related'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for Strategy and External Communications to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Strategy and External Communications","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Strategy and External Communications","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0024',
    reference_id: 'JPHRC/IMS/2026/0024',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Asset'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Expiry of reagents',
    incident_category: 'Lab Related',
    incident_types: ['Expiry of reagents'],
    incident_categories: ['Lab Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Asset to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Asset","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Asset","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0025',
    reference_id: 'JPHRC/IMS/2026/0025',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['JPIEE'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate exposure to radiation',
    incident_category: 'Radiology Related',
    incident_types: ['Inappropriate exposure to radiation'],
    incident_categories: ['Radiology Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor resolved incident reported for JPIEE to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD JPIEE","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD JPIEE","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0026',
    reference_id: 'JPHRC/IMS/2026/0026',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'dispute',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Lab Medicine'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Misuse of amenities',
    incident_category: 'Facility Related',
    incident_types: ['Misuse of amenities'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Staff',
    description: 'Sample Major dispute incident reported for Lab Medicine to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Lab Medicine","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Lab Medicine","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0027',
    reference_id: 'JPHRC/IMS/2026/0027',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'redirect_requested',
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Blood Centre'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'MLC related notes',
    incident_category: 'Doctor Related',
    incident_types: ['MLC related notes'],
    incident_categories: ['Doctor Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave redirect_requested incident reported for Blood Centre to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Blood Centre","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"Redirect Requested","by":"HOD Blood Centre","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0028',
    reference_id: 'JPHRC/IMS/2026/0028',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Radiology'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Others'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for Radiology to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0029',
    reference_id: 'JPHRC/IMS/2026/0029',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['MD Office'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Material/Consumable/ Drug not available before surgery',
    incident_category: 'Surgery or Procedure Related',
    incident_types: ['Material/Consumable/ Drug not available before surgery'],
    incident_categories: ['Surgery or Procedure Related'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for MD Office to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0030',
    reference_id: 'JPHRC/IMS/2026/0030',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Infection Control and Microbiology'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Prolonged non-availability of critical medical equipment',
    incident_category: 'Asset Related',
    incident_types: ['Prolonged non-availability of critical medical equipment'],
    incident_categories: ['Asset Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Infection Control and Microbiology to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Infection Control and Microbiology","timestamp":"2026-05-30T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0031',
    reference_id: 'JPHRC/IMS/2026/0031',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Medical Services'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Classification of Incident',
    incident_types: ['Others'],
    incident_categories: ['Classification of Incident'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Medical Services to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Medical Services","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Medical Services","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0032',
    reference_id: 'JPHRC/IMS/2026/0032',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Nursing Services'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Blood Bank Related',
    incident_types: ['Others'],
    incident_categories: ['Blood Bank Related'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for Nursing Services to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Nursing Services","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Nursing Services","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0033',
    reference_id: 'JPHRC/IMS/2026/0033',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Purchase'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'OT notes',
    incident_category: 'Doctor Related',
    incident_types: ['OT notes'],
    incident_categories: ['Doctor Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Purchase to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Purchase","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Purchase","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0034',
    reference_id: 'JPHRC/IMS/2026/0034',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Finance and Accounts'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Ambulance medical equipment non-functional/non-available Delayed ambulance/vehicle service',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Ambulance medical equipment non-functional/non-available Delayed ambulance/vehicle service'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor resolved incident reported for Finance and Accounts to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Finance and Accounts","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Finance and Accounts","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0035',
    reference_id: 'JPHRC/IMS/2026/0035',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'dispute',
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Public Relations'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Wrong investigation/procedure/consultation',
    incident_category: 'Billing Related',
    incident_types: ['Wrong investigation/procedure/consultation'],
    incident_categories: ['Billing Related'],
    occurred_to: 'Staff',
    description: 'Sample Major dispute incident reported for Public Relations to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Public Relations","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Public Relations","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0036',
    reference_id: 'JPHRC/IMS/2026/0036',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'redirect_requested',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Legal Cell'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Government credit patient related billing error',
    incident_category: 'Billing Related',
    incident_types: ['Government credit patient related billing error'],
    incident_categories: ['Billing Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave redirect_requested incident reported for Legal Cell to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Legal Cell","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"Redirect Requested","by":"HOD Legal Cell","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0037',
    reference_id: 'JPHRC/IMS/2026/0037',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Corporate Relations and Business Development'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Documentation related',
    incident_category: 'Blood Bank Related',
    incident_types: ['Documentation related'],
    incident_categories: ['Blood Bank Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for Corporate Relations and Business Development to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0038',
    reference_id: 'JPHRC/IMS/2026/0038',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 23 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Human Resource'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inaccurate or out-of-calibration equipment',
    incident_category: 'Asset Related',
    incident_types: ['Inaccurate or out-of-calibration equipment'],
    incident_categories: ['Asset Related'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for Human Resource to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0039',
    reference_id: 'JPHRC/IMS/2026/0039',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Facility'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Untimely delivery of linen',
    incident_category: 'Laundry and Linen related',
    incident_types: ['Untimely delivery of linen'],
    incident_categories: ['Laundry and Linen related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Facility to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Facility","timestamp":"2026-05-30T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0040',
    reference_id: 'JPHRC/IMS/2026/0040',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Food and Beverages'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Poor Quality of linen',
    incident_category: 'Laundry and Linen related',
    incident_types: ['Poor Quality of linen'],
    incident_categories: ['Laundry and Linen related'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Food and Beverages to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Food and Beverages","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Food and Beverages","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0041',
    reference_id: 'JPHRC/IMS/2026/0041',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Housekeeping'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Classification of Incident',
    incident_types: ['Others'],
    incident_categories: ['Classification of Incident'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for Housekeeping to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Housekeeping","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Housekeeping","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0042',
    reference_id: 'JPHRC/IMS/2026/0042',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Linen and Laundry'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Rash driving/accident',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Rash driving/accident'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Linen and Laundry to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Linen and Laundry","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Linen and Laundry","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0043',
    reference_id: 'JPHRC/IMS/2026/0043',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Ambulance / Travel / Transport'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate procedure',
    incident_category: 'Radiology Related',
    incident_types: ['Inappropriate procedure'],
    incident_categories: ['Radiology Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor resolved incident reported for Ambulance / Travel / Transport to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Ambulance / Travel / Transport","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Ambulance / Travel / Transport","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0044',
    reference_id: 'JPHRC/IMS/2026/0044',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'dispute',
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Security Services'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Incorrect consent form/s used Incomplete consent form',
    incident_category: 'Consent Related',
    incident_types: ['Incorrect consent form/s used Incomplete consent form'],
    incident_categories: ['Consent Related'],
    occurred_to: 'Staff',
    description: 'Sample Major dispute incident reported for Security Services to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Security Services","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Security Services","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0045',
    reference_id: 'JPHRC/IMS/2026/0045',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'redirect_requested',
    created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Quality Management'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Delayed Response to Complaints/Request',
    incident_category: 'Facility Related',
    incident_types: ['Delayed Response to Complaints/Request'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave redirect_requested incident reported for Quality Management to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Quality Management","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"Redirect Requested","by":"HOD Quality Management","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0046',
    reference_id: 'JPHRC/IMS/2026/0046',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Training and Development'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate delay in procurement of item',
    incident_category: 'Store Related',
    incident_types: ['Inappropriate delay in procurement of item'],
    incident_categories: ['Store Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for Training and Development to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0047',
    reference_id: 'JPHRC/IMS/2026/0047',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 29 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Stores'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Classification of Incident',
    incident_types: ['Others'],
    incident_categories: ['Classification of Incident'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for Stores to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0048',
    reference_id: 'JPHRC/IMS/2026/0048',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Fire Safety'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Classification of Incident',
    incident_types: ['Others'],
    incident_categories: ['Classification of Incident'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Fire Safety to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Fire Safety","timestamp":"2026-05-30T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0049',
    reference_id: 'JPHRC/IMS/2026/0049',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 27 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Patient Care'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Blood Bank Related',
    incident_types: ['Others'],
    incident_categories: ['Blood Bank Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Patient Care to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Patient Care","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Patient Care","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0050',
    reference_id: 'JPHRC/IMS/2026/0050',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['General Maintenance'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Prolonged non-availability of item',
    incident_category: 'Purchase Related',
    incident_types: ['Prolonged non-availability of item'],
    incident_categories: ['Purchase Related'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for General Maintenance to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD General Maintenance","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD General Maintenance","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0051',
    reference_id: 'JPHRC/IMS/2026/0051',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Bio-Medical'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Incorrect sample collection',
    incident_category: 'Nursing Document Related',
    incident_types: ['Incorrect sample collection'],
    incident_categories: ['Nursing Document Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Bio-Medical to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Bio-Medical","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Bio-Medical","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0052',
    reference_id: 'JPHRC/IMS/2026/0052',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Digital Communications'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'Vehicle and Ambulance Related',
    incident_types: ['Others'],
    incident_categories: ['Vehicle and Ambulance Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor resolved incident reported for Digital Communications to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Digital Communications","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Digital Communications","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0053',
    reference_id: 'JPHRC/IMS/2026/0053',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'dispute',
    created_at: new Date(Date.now() - 23 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Strategy and External Communications'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Unauthorised movement of equipment/accessories',
    incident_category: 'Biomedical Related',
    incident_types: ['Unauthorised movement of equipment/accessories'],
    incident_categories: ['Biomedical Related'],
    occurred_to: 'Staff',
    description: 'Sample Major dispute incident reported for Strategy and External Communications to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Strategy and External Communications","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Strategy and External Communications","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0054',
    reference_id: 'JPHRC/IMS/2026/0054',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'redirect_requested',
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Asset'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Code Blue',
    incident_category: 'Hospital Emergency Codes Related',
    incident_types: ['Code Blue'],
    incident_categories: ['Hospital Emergency Codes Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave redirect_requested incident reported for Asset to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Asset","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"Redirect Requested","by":"HOD Asset","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0055',
    reference_id: 'JPHRC/IMS/2026/0055',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['JPIEE'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Unauthorized encroachment of accommodation/amenities',
    incident_category: 'Facility Related',
    incident_types: ['Unauthorized encroachment of accommodation/amenities'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor submitted incident reported for JPIEE to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0056',
    reference_id: 'JPHRC/IMS/2026/0056',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'submitted',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Lab Medicine'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Sample related',
    incident_category: 'Lab Related',
    incident_types: ['Sample related'],
    incident_categories: ['Lab Related'],
    occurred_to: 'Staff',
    description: 'Sample Major submitted incident reported for Lab Medicine to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0057',
    reference_id: 'JPHRC/IMS/2026/0057',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_hod',
    created_at: new Date(Date.now() - 19 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Blood Centre'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Unauthorized encroachment of accommodation/amenities',
    incident_category: 'Facility Related',
    incident_types: ['Unauthorized encroachment of accommodation/amenities'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave with_hod incident reported for Blood Centre to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: null,
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Blood Centre","timestamp":"2026-05-30T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0058',
    reference_id: 'JPHRC/IMS/2026/0058',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Radiology'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Others',
    incident_category: 'CSSD Related',
    incident_types: ['Others'],
    incident_categories: ['CSSD Related'],
    occurred_to: 'Patient',
    description: 'Sample Minor with_imc incident reported for Radiology to demonstrate dashboard analytics.',
    severity: 'Minor',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Radiology","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Radiology","timestamp":"2026-06-04T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0059',
    reference_id: 'JPHRC/IMS/2026/0059',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_head_management',
    created_at: new Date(Date.now() - 17 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['MD Office'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Inappropriate documentation',
    incident_category: 'Purchase Related',
    incident_types: ['Inappropriate documentation'],
    incident_categories: ['Purchase Related'],
    occurred_to: 'Staff',
    description: 'Sample Major with_head_management incident reported for MD Office to demonstrate dashboard analytics.',
    severity: 'Major',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: null,
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD MD Office","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD MD Office","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0060',
    reference_id: 'JPHRC/IMS/2026/0060',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'resolved',
    created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: '1st Floor',
    departments: ['Infection Control and Microbiology'],
    location: 'MAIN Hospital Danidiapali - 1st Floor',
    incident_type: 'Unauthorized movement of facility item',
    incident_category: 'Facility Related',
    incident_types: ['Unauthorized movement of facility item'],
    incident_categories: ['Facility Related'],
    occurred_to: 'Visitor',
    description: 'Sample Grave resolved incident reported for Infection Control and Microbiology to demonstrate dashboard analytics.',
    severity: 'Grave',
    hod_feedback: 'Forwarding to IMC for further investigation.',
    imc_feedback: 'Reviewed by IMC. Recommending management decision.',
    management_feedback: 'Corrective action taken. Incident closed.',
    workflow_history: [{"action":"Reported","by":"NIRMAL NAIK","timestamp":"2026-05-25T05:21:20.304Z"},{"action":"HOD Viewed","by":"HOD Infection Control and Microbiology","timestamp":"2026-05-30T05:21:20.304Z"},{"action":"HOD Reviewed","by":"HOD Infection Control and Microbiology","timestamp":"2026-06-04T05:21:20.304Z"},{"action":"IMC Processed","by":"IMC Committee","timestamp":"2026-06-09T05:21:20.304Z"},{"action":"Resolved","by":"Management","timestamp":"2026-06-19T05:21:20.304Z"}]
  },
  {
    id: 'JPHRC/IMS/2026/0061',
    reference_id: 'JPHRC/IMS/2026/0061',
    reporter_id: '1',
    reporter_name: 'NIRMAL NAIK',
    reporter_department: 'Digital Communications',
    reporter_employee_id: '13574',
    status: 'with_imc',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    main_location_name: 'MAIN Hospital Danidiapali',
    sub_location_name: 'Ward C',
    departments: ['Nursing Services'],
    location: 'MAIN Hospital Danidiapali - Ward C',
    incident_type: 'Error/Delay during administration',
    incident_category: 'Medication Related',
    incident_types: ['Error/Delay during administration'],
    incident_categories: ['Medication Related'],
    occurred_to: 'Patient',
    has_responsible_person: true,
    responsible_person_name: 'Nurse Priya (Emp ID: 11205)',
    training_completed: false,
    description: 'Nurse Priya administered the incorrect dosage of medication to the patient due to a misread prescription chart. No adverse reaction occurred, but this is a critical near-miss. Root cause: Human Error.',
    severity: 'Major',
    hod_feedback: 'Investigated the matter. It was a human error by Nurse Priya. Recommending mandatory refresher training on medication administration protocols before she can resume independent duties.',
    imc_feedback: null,
    management_feedback: null,
    workflow_history: [
      {"action":"Reported","by":"NIRMAL NAIK","timestamp": new Date(Date.now() - 5 * 86400000).toISOString()},
      {"action":"HOD Viewed","by":"HOD Nursing Services","timestamp": new Date(Date.now() - 4 * 86400000).toISOString()},
      {"action":"HOD Reviewed","by":"HOD Nursing Services","timestamp": new Date(Date.now() - 3 * 86400000).toISOString()}
    ]
  }
];

const savedIncidents = localStorage.getItem('ims_incidents');
let parsed = savedIncidents ? JSON.parse(savedIncidents) : null;

// Invalidate outdated cached mock data that used generic 'Clinical'/'Non-Clinical' types
if (parsed && parsed.some(i => i.incident_type === 'Clinical' || i.incident_type === 'Non-Clinical')) {
  parsed = null;
  localStorage.removeItem('ims_incidents');
}

export let mockIncidents = (parsed && parsed.length > 0) ? parsed : initialMockIncidents;

// Sort globally so newest incidents (highest ID/date) appear first
mockIncidents.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

// Ensure all mock incidents have an incident_date for display purposes
mockIncidents.forEach(inc => {
  if (!inc.incident_date) inc.incident_date = inc.created_at;
});

const savedNotifications = localStorage.getItem('ims_notifications');
export let mockNotifications = savedNotifications ? JSON.parse(savedNotifications) : [];

export const mockLocations = {
  mainLocations: [
    { id: 1, name: 'MAIN Hospital Danidiapali' },
    { id: 2, name: 'City Center Uditnagar' },
    { id: 3, name: 'City Center Rajgangpur' }
  ],
  subLocations: [
    { id: 1, main_location_id: 1, name: '1st Floor' },
    { id: 2, main_location_id: 1, name: '2nd Floor' },
    { id: 3, main_location_id: 1, name: 'ICU' },
    { id: 4, main_location_id: 1, name: 'Ward C' },
    { id: 5, main_location_id: 1, name: 'OT 1' },
    { id: 6, main_location_id: 1, name: 'OT 2' },
    { id: 7, main_location_id: 2, name: 'Ground Floor OPD' },
    { id: 8, main_location_id: 2, name: 'Pharmacy' },
    { id: 9, main_location_id: 2, name: 'Consultation Room' },
    { id: 10, main_location_id: 3, name: 'Emergency Room' },
    { id: 11, main_location_id: 3, name: 'General Ward' },
    { id: 12, main_location_id: 3, name: 'Reception' }
  ]
};

export const mockDepartments = [
  { id: 1, name: 'Medical Services' },
  { id: 2, name: 'Nursing Services' },
  { id: 3, name: 'Purchase' },
  { id: 4, name: 'Finance and Accounts' },
  { id: 5, name: 'Public Relations' },
  { id: 6, name: 'Legal Cell' },
  { id: 7, name: 'Corporate Relations and Business Development' },
  { id: 8, name: 'Human Resource' },
  { id: 9, name: 'Facility' },
  { id: 10, name: 'Food and Beverages' },
  { id: 11, name: 'Housekeeping' },
  { id: 12, name: 'Linen and Laundry' },
  { id: 13, name: 'Ambulance / Travel / Transport' },
  { id: 14, name: 'Security Services' },
  { id: 15, name: 'Quality Management' },
  { id: 16, name: 'Training and Development' },
  { id: 17, name: 'Stores' },
  { id: 18, name: 'Fire Safety' },
  { id: 19, name: 'Patient Care' },
  { id: 20, name: 'General Maintenance' },
  { id: 21, name: 'Bio-Medical' },
  { id: 22, name: 'Digital Communications' },
  { id: 23, name: 'Strategy and External Communications' },
  { id: 24, name: 'Asset' },
  { id: 25, name: 'JPIEE' },
  { id: 26, name: 'Lab Medicine' },
  { id: 27, name: 'Blood Centre' },
  { id: 28, name: 'Radiology' },
  { id: 29, name: 'MD Office' },
  { id: 30, name: 'Infection Control and Microbiology' }
];

export const mockDesignations = [
  { id: 1, name: 'Consultant - D1 to D3' },
  { id: 2, name: 'Sr. Medical Officer - D4' },
  { id: 3, name: 'Jr. Medical Officer - D5' },
  { id: 4, name: 'Clinical Assistant - D6' },
  { id: 5, name: 'Infection Control Nurse' },
  { id: 6, name: 'Nursing Sup. - NS1' },
  { id: 7, name: 'Deputy Nursing Sup. - NS2' },
  { id: 8, name: 'Asst. Nursing Sup. - NS3' },
  { id: 9, name: 'Ward In-charge - NS4' },
  { id: 10, name: 'Sr. Nurse - NS5' },
  { id: 11, name: 'Jr. Nurse - NS6' },
  { id: 12, name: 'Nursing Assistant - NS7' },
  { id: 13, name: 'Health Assistant - NS8' },
  { id: 14, name: 'Sr. Technician' },
  { id: 15, name: 'Jr. Technician' },
  { id: 16, name: 'Technical Assistant' },
  { id: 17, name: 'HOD' },
  { id: 18, name: 'Assistant HOD' },
  { id: 19, name: 'In-charge' },
  { id: 20, name: 'Assistant In-charge' },
  { id: 21, name: 'Senior Co-Ordinator' },
  { id: 22, name: 'Junior Co-Ordinator' },
  { id: 23, name: 'Department Assistant' },
  { id: 24, name: 'MPW' },
  { id: 25, name: 'DNB Doctor' },
  { id: 26, name: 'COO' },
  { id: 27, name: 'Assistant COO' },
  { id: 28, name: 'Others' }
];

export let mockKbArticles = [
  {
    id: 1,
    title: 'How to report a Patient Fall',
    content: 'Ensure you fill out the location and time accurately...',
    category: 'Guidelines',
    created_at: new Date().toISOString()
  }
];

export const mockTraining = [
  {
    id: 1,
    title: 'Fire Safety Protocols 2026',
    description: 'Mandatory training for all staff regarding fire safety.',
    completed: false
  }
];
